### ISSUE TITLE
Or operator inside value

### ISSUE THREAD

**Issue by paulm17** [hopkinsth/go-ruler#2]
Out of the other rule packages, I found this the best one for my needs.  So thank you for developing it.

I have one use-case which I'm sure complicates things further.

I needed the ability to match multiple values within a rule.

For example.  I may have the requirement of:

Expected -
People: Elon Musk OR Bill Gates OR Marissa Mayer
AND
Gender: Male

Actual - 
People: Elon Musk
Gender: Male

I modified the compare method in ruler.go.

```
case "eq":
    if strings.Contains(expected.(string), ",") {
        sExpected := strings.Split(expected.(string), ",")

        for _, item := range sExpected {
            if strings.EqualFold(actual.(string), item) {
                return true
            }
        }

        return false
    }

    return actual == expected
```

Here is an example:

```
package main

import "github.com/hopkinsth/go-ruler"
import "fmt"

func main() {
    // can also build rules programmatically
    engine := ruler.NewRuler(nil)

    engine.Rule("name").Eq("Elon Musk,Bill Gates,Marissa Mayer")
    engine.Rule("gender").Eq("male")

    context := map[string]interface{}{
        "name":   "Bill Gates",
        "gender": "male",
    }

    result := engine.Test(context)

    fmt.Println(result == true)
}
```

Or perhaps you want to do something else?  But maybe you'll come up with something better and that all other compare methods can use.

Thanks again!

**Comment by hopkinsth** [comment]
Are you mostly building rules programmatically, or are you using the JSON input? Or both?

This would be a good feature to have, but I would prefer to avoid overloading the value field in this way. I have existing uses in production that rely on being able to compare strings with commas in them as the whole string rather than as a list of alternates. 

I would prefer an API that looks something like this:

``` go
engine := ruler.NewRuler(nil)
engine.Rule("name").
  .Eq("Elon Musk").Or()
  .Eq("Bill Gates").Or()
  .Eq("Marissa Mayer")
```

Ideally this would also change or build on top of the structure of the rule JSON. I propose the latter, so in addition to JSON that looks like this:

``` json
{"comparator": "eq", "path": "name", "value": "Bill Gates"}
```

you could also do something like this...

``` json
{
  "require": "(all | any)",
  "rules": [{
    "comparator": "eq",
    "path": "name",
    "value": "Bill Gates"
  }, {
    "comparator": "eq",
    "path": "name",
    "value": "Elon Musk"
  }, {
    "comparator": "eq",
    "path": "name",
    "value": "Marissa Mayer"
  }]
}
```

While this may be more verbose than simply using an array of possible values, I prefer it because it lets this library have nested rulesets (with different ANY vs. ALL conditions) easily as a result.

The only tricky thing about implementing that is that this library still needs to support parsing a JSON array of conditions and turning them into a single ruleset for evaluation. I have existing things that rely on that behavior. It's probably quick enough to compare the first non-nil, non-whitespace byte of JSON input against the `[` or `{` character to know how to decode it.

Anyway, I'm kinda thinking out loud there. I'll work on this sometime soon.

**Comment by paulm17** [comment]
Thanks for getting back.

I am building this programmatically from a database.

I'm looping through a bunch of rules and the criteria multiples exist within that:

```
for _, rrule := range ruleset.Rule {
    engine := ruler.NewRuler(nil)

    for _, criteria := range rrule.Criteria {
        values := strings.Join(criteria.Values, ",")

        if criteria.Condition == "equalto" {
            engine.Rule(criteria.Parameter).Eq(values)
        } else if criteria.Condition == "notequalto" {
            engine.Rule(criteria.Parameter).Neq(values)
        } else if criteria.Condition == "contains" {
            engine.Rule(criteria.Parameter).Matches(values)
        }
    }

    result := engine.Test(context)

    if result {
        ....

    }
}
```

As you can see, chaining doesn't work for me.  The comma separated values work because that's what I get from the DB.

I don't use JSON.  No need to retrieve from the db and then put into JSON and then loop through it.  I see that as an extra step.

What would be nice for me, is what you propose but also when not wanting to use JSON or chaining:

```
engine.Require("all | any")
engine.Rule("name").Eq("Bill Gates")        
engine.Rule("name").Eq("Elon Musk")     
engine.Rule("name").Eq("Marissa Mayer")     
```

But I am not sure if this is possible.

**Comment by hopkinsth** [comment]
I think that could work but may require restructuring some things – I'll need to work through this. The model for how this would work could be something closer to [https://github.com/rfink/verdict.js](verdict.js), which would give an API like this...

``` go
r1 := ruler.NewRuler(nil)
r1.Any()
r1.Rule("name").Eq("Bill Gates")
r1.Rule("name").Eq("Marissa Mayer")

r2 := ruler.NewRuler(nil)
r2.All() // this is the default
r2.Rule("name").Eq("Elon Musk")

main := ruler.NewRuler(nil)
main.All(r1, r2)
main.Test() 

// also, 
main = ruler.NewRuler(r1, r2)
main.Test()
```

I think that should give you what you need here.

**Comment by paulm17** [comment]
I think this is fine!  Take your time on the changes.  The modification I made is fine for now.  But as soon as you do the changes, I'll re-implement and give feedback!
